#!/bin/bash

set -e

# Check if already authenticated
if gh auth status &>/dev/null; then
  echo "✅ Already logged into GitHub."
else
  echo "🔐 Not logged in. Logging in via browser..."
  gh auth login --hostname github.com --git-protocol https --web

  # Recheck login status
  if ! gh auth status &>/dev/null; then
    echo "❌ GitHub login failed."
    exit 1
  fi
  echo "✅ Logged into GitHub."
fi

gh release list

# Fetch latest tags and branches
git fetch --prune origin "+refs/tags/*:refs/tags/*"
git fetch --prune origin

# Get the latest version tag (e.g., v1.0.7)
latest_tag=$(git describe --tags "$(git rev-list --tags --max-count=1)" 2>/dev/null || echo "")
echo "Latest release tag is: ${latest_tag:-None}"

# Attempt to parse semantic version and increment patch
version="${latest_tag#v}"  # remove leading 'v'

IFS='.' read -r major minor patch <<< "$version"

if [[ "$major" =~ ^[0-9]+$ && "$minor" =~ ^[0-9]+$ && "$patch" =~ ^[0-9]+$ ]]; then
  patch=$((patch + 1))
  next_version="v$major.$minor.$patch"
else
  next_version=""
fi

# Prompt user for a new version, show default if parsed successfully
read -p "Enter new version${next_version:+ (default: $next_version)}: " new_version

# Use default if no input and default exists
if [ -z "$new_version" ] && [ -n "$next_version" ]; then
  new_version=$next_version
fi

# Validate new_version non-empty
if [ -z "$new_version" ]; then
  echo "No version entered. Exiting."
  exit 1
fi

new_tag="$new_version"
branch_name="release-$new_tag"

echo "Creating new release branch: $branch_name"
read -p "Continue? (y/n) [y]: " confirm
confirm=${confirm:-y}   # default to 'y' if empty input
if [[ "$confirm" != "y" ]]; then
  echo "Cancelled."
  exit 1
fi

# Create new branch from latest main
git checkout origin/main -b "$branch_name"
git push -u origin "$branch_name"

# Create an annotated tag
git tag -a "$new_tag" -m "Release $new_tag"
git push origin "$new_tag"

# Create GitHub release with autogenerated notes
gh release create "$new_tag" \
  --title "Release $new_tag" \
  --target "$branch_name" \
  --generate-notes

echo "✅ Release $new_tag created successfully!"
