import { removeHtmlTags } from 'utils/string';
import { GridColDef } from '.';
import { GridValidRowModel } from '@mui/x-data-grid';

export const thaiLocaleText = {
  noRowsLabel: 'ไม่มีข้อมูลแสดงผล',
  noResultsOverlayLabel: 'ไม่พบผลลัพธ์',
  toolbarDensity: 'ความหนาแน่น',
  toolbarDensityLabel: 'ความหนาแน่น',
  toolbarDensityCompact: 'แคบ',
  toolbarDensityStandard: 'ปกติ',
  toolbarDensityComfortable: 'กว้าง',
  toolbarColumns: 'คอลัมน์',
  toolbarColumnsLabel: 'เลือกคอลัมน์',
  toolbarFilters: 'ตัวกรอง',
  toolbarFiltersLabel: 'แสดงตัวกรอง',
  toolbarFiltersTooltipHide: 'ซ่อนตัวกรอง',
  toolbarFiltersTooltipShow: 'แสดงตัวกรอง',
  toolbarFiltersTooltipActive: (count: number) => `${count} ตัวกรองที่ใช้งานอยู่`,
  toolbarQuickFilterPlaceholder: 'ค้นหา…',
  toolbarQuickFilterLabel: 'ค้นหา',
  toolbarQuickFilterDeleteIconLabel: 'ล้าง',
  toolbarExport: 'ส่งออก',
  toolbarExportLabel: 'ส่งออก',
  toolbarExportCSV: 'ดาวน์โหลด CSV',
  toolbarExportPrint: 'พิมพ์',
  toolbarExportExcel: 'ดาวน์โหลด Excel',
  columnsManagementSearchTitle: 'ค้นหาคอลัมน์',
  columnsManagementNoColumns: 'ไม่มีคอลัมน์',
  columnsManagementShowHideAllText: 'แสดง/ซ่อนทั้งหมด',
  columnsManagementReset: 'รีเซ็ต',
  columnsManagementDeleteIconLabel: 'ลบ',
  filterPanelAddFilter: 'เพิ่มตัวกรอง',
  filterPanelRemoveAll: 'ลบทั้งหมด',
  filterPanelDeleteIconLabel: 'ลบ',
  filterPanelLogicOperator: 'ตัวดำเนินการทางตรรกะ',
  filterPanelOperator: 'ตัวดำเนินการ',
  filterPanelOperatorAnd: 'และ',
  filterPanelOperatorOr: 'หรือ',
  filterPanelColumns: 'คอลัมน์',
  filterPanelInputLabel: 'ค่า',
  filterPanelInputPlaceholder: 'กรอกค่า',
  filterOperatorContains: 'มีคำว่า',
  filterOperatorDoesNotContain: 'ไม่มีคำว่า',
  filterOperatorEquals: 'เท่ากับ',
  filterOperatorDoesNotEqual: 'ไม่เท่ากับ',
  filterOperatorStartsWith: 'เริ่มต้นด้วย',
  filterOperatorEndsWith: 'ลงท้ายด้วย',
  filterOperatorIs: 'คือ',
  filterOperatorNot: 'ไม่ใช่',
  filterOperatorAfter: 'หลังจาก',
  filterOperatorOnOrAfter: 'ในหรือหลังจาก',
  filterOperatorBefore: 'ก่อนหน้า',
  filterOperatorOnOrBefore: 'ในหรือก่อนหน้า',
  filterOperatorIsEmpty: 'ว่างเปล่า',
  filterOperatorIsNotEmpty: 'ไม่ว่างเปล่า',
  filterOperatorIsAnyOf: 'เป็นหนึ่งใน',
  'filterOperator=': '=',
  'filterOperator!=': '≠',
  'filterOperator>': '>',
  'filterOperator>=': '≥',
  'filterOperator<': '<',
  'filterOperator<=': '≤',
  headerFilterOperatorContains: 'มีคำว่า',
  headerFilterOperatorDoesNotContain: 'ไม่มีคำว่า',
  headerFilterOperatorEquals: 'เท่ากับ',
  headerFilterOperatorDoesNotEqual: 'ไม่เท่ากับ',
  headerFilterOperatorStartsWith: 'เริ่มต้นด้วย',
  headerFilterOperatorEndsWith: 'ลงท้ายด้วย',
  headerFilterOperatorIs: 'คือ',
  headerFilterOperatorNot: 'ไม่ใช่',
  headerFilterOperatorAfter: 'หลังจาก',
  headerFilterOperatorOnOrAfter: 'ในหรือหลังจาก',
  headerFilterOperatorBefore: 'ก่อนหน้า',
  headerFilterOperatorOnOrBefore: 'ในหรือก่อนหน้า',
  headerFilterOperatorIsEmpty: 'ว่างเปล่า',
  headerFilterOperatorIsNotEmpty: 'ไม่ว่างเปล่า',
  headerFilterOperatorIsAnyOf: 'เป็นหนึ่งใน',
  'headerFilterOperator=': '=',
  'headerFilterOperator!=': '≠',
  'headerFilterOperator>': '>',
  'headerFilterOperator>=': '≥',
  'headerFilterOperator<': '<',
  'headerFilterOperator<=': '≤',
  filterValueAny: 'ใด ๆ',
  filterValueTrue: 'จริง',
  filterValueFalse: 'เท็จ',
  columnMenuLabel: 'เมนู',
  columnMenuAriaLabel: (columnName: string) => `เมนูของคอลัมน์ ${columnName}`,
  columnMenuShowColumns: 'แสดงคอลัมน์',
  columnMenuManageColumns: 'จัดการคอลัมน์',
  columnMenuFilter: 'กรอง',
  columnMenuHideColumn: 'ซ่อนคอลัมน์',
  columnMenuUnsort: 'ล้างการจัดเรียง',
  columnMenuSortAsc: 'เรียงจากน้อยไปมาก',
  columnMenuSortDesc: 'เรียงจากมากไปน้อย',
  columnHeaderFiltersTooltipActive: (count: number) => `${count} ตัวกรองที่ใช้งานอยู่`,
  columnHeaderFiltersLabel: 'แสดงตัวกรอง',
  columnHeaderSortIconLabel: 'จัดเรียง',
  footerRowSelected: (count: number) => `เลือก ${count} แถว`,
  footerTotalRows: 'รวมทั้งหมด:',
  footerTotalVisibleRows: (visibleCount: number, totalCount: number) =>
    `${visibleCount} จาก ${totalCount}`,
  checkboxSelectionHeaderName: 'เลือกแถว',
  checkboxSelectionSelectAllRows: 'เลือกทุกแถว',
  checkboxSelectionUnselectAllRows: 'ยกเลิกการเลือกทุกแถว',
  checkboxSelectionSelectRow: 'เลือกแถว',
  checkboxSelectionUnselectRow: 'ยกเลิกการเลือกแถว',
  booleanCellTrueLabel: 'จริง',
  booleanCellFalseLabel: 'เท็จ',
  actionsCellMore: 'เพิ่มเติม',
  pinToLeft: 'ปักหมุดซ้าย',
  pinToRight: 'ปักหมุดขวา',
  unpin: 'ยกเลิกปักหมุด',
  treeDataGroupingHeaderName: 'โครงสร้างต้นไม้',
  treeDataExpand: 'แสดง',
  treeDataCollapse: 'ย่อ',
  groupingColumnHeaderName: 'กลุ่ม',
  groupColumn: (name: string) => `จัดกลุ่มตาม ${name}`,
  unGroupColumn: (name: string) => `ยกเลิกกลุ่มจาก ${name}`,
  detailPanelToggle: 'แสดงรายละเอียด',
  expandDetailPanel: 'ขยาย',
  collapseDetailPanel: 'ย่อ',
  rowReorderingHeaderName: 'ลากเพื่อจัดเรียง',
  aggregationMenuItemHeader: 'การรวม',
  aggregationFunctionLabelSum: 'รวม',
  aggregationFunctionLabelAvg: 'เฉลี่ย',
  aggregationFunctionLabelMin: 'ค่าต่ำสุด',
  aggregationFunctionLabelMax: 'ค่าสูงสุด',
  aggregationFunctionLabelSize: 'จำนวน',
};

const EMPTY_TEXT = '--';

export const withEmptyRender = <T extends GridValidRowModel>(
  columns: GridColDef<T>[]
): GridColDef<T>[] => {
  return columns.map(({ renderCell, ...col }) => ({
    ...col,
    renderCell: (params) => {
      if (renderCell) {
        const content = renderCell(params);
        const contentString = content?.toString() ?? '';
        const isContentValid = removeHtmlTags(contentString).length > 0;
        return isContentValid ? content : EMPTY_TEXT;
      }
      if (typeof params.value === 'string') return params.value.trim() || EMPTY_TEXT;
      return params.value ?? EMPTY_TEXT;
    },
  }));
};
